name: clean-js
on: push
jobs:
  clean-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove newlines from script.js
        run: tr -d "\n\r" < script.js
